// <auto-generated />
namespace H2Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class punishmentpeirod_create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(punishmentpeirod_create));
        
        string IMigrationMetadata.Id
        {
            get { return "201808280614024_punishmentpeirod_create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
