// <auto-generated />
namespace H2Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatetableName_h2moduleaudutingwith : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetableName_h2moduleaudutingwith));
        
        string IMigrationMetadata.Id
        {
            get { return "201903290254325_updatetableName_h2moduleaudutingwith"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
