// <auto-generated />
namespace H2Service.MigrationsMysql
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class testsremove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testsremove));
        
        string IMigrationMetadata.Id
        {
            get { return "201903310647302_testsremove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
