// <auto-generated />
namespace H2Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addmodel51 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmodel51));
        
        string IMigrationMetadata.Id
        {
            get { return "201910161219460_addmodel51"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
