// <auto-generated />
namespace H2Service.MigrationsMysql
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class validatetype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validatetype));
        
        string IMigrationMetadata.Id
        {
            get { return "201905220750262_validatetype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
